import './globals.css'
import { Analytics } from '@vercel/analytics/next'

export const metadata = {
  title: 'App',
  description: 'Generated by AI',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  )
}